CREATE TABLE PEOPLE (
  PERSON_ID         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME        VARCHAR(20),
  LAST_NAME         VARCHAR(20),
  ADDRESS_LINE_1    VARCHAR(20),
  ADDRESS_LINE_2    VARCHAR(100),
  PHONE_NUMBER      VARCHAR(10),
  CITY              VARCHAR(20),
  STATE             VARCHAR(2),
  ZIP_CODE          VARCHAR(5)
);
